# Generated by Django 3.0 on 2020-03-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('IND', 'Individual'), ('DOB', 'Doble'), ('TRIP', 'Triple'), ('CUAD', 'Cuádruple')], max_length=4)),
                ('price', models.DecimalField(decimal_places=0, max_digits=2)),
                ('capacity', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('locator', models.CharField(max_length=50, unique=True)),
                ('room_number', models.IntegerField()),
                ('guest_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Guest')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.RoomType')),
            ],
        ),
    ]
