# Generated by Django 3.0 on 2020-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='number_guests',
        ),
        migrations.AlterField(
            model_name='booking',
            name='locator',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
