# Generated by Django 3.0 on 2020-03-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20200301_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('DOBLE', 'Doble'), ('TRIPLE', 'Triple'), ('CUADRUPLE', 'Cuádruple')], max_length=15),
        ),
    ]
